export const GET_MOVIESHOWTIMES_LIST = 'GET_MOVIESHOWTIMES_LIST';
export const CREATE_MOVIESHOWTIME = 'CREATE_MOVIESHOWTIME';
export const UPDATE_MOVIESHOWTIME = 'UPDATE_MOVIESHOWTIME';
export const DELETE_MOVIESHOWTIME = 'DELETE_MOVIESHOWTIME';

// export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
// export const SELECT_MOVIESHOWTIMES = 'SELECT_MOVIESHOWTIMES';
// export const SELECT_ALL_MOVIESHOWTIMES = 'SELECT_ALL_MOVIESHOWTIMES';