export const GET_THEATERS_LIST = 'GET_THEATERS_LIST';
export const GET_THEATER_INFO = 'GET_THEATER_INFO';
export const CREATE_THEATER = 'CREATE_THEATER';
export const UPDATE_THEATER = 'UPDATE_THEATER';
export const DELETE_THEATER = 'DELETE_THEATER';