export const GET_USERS_INFO_LIST = 'GET_USERS_LIST';
export const GET_USER_INFO='GET_USER_INFO'
export const CREATE_USER_INFO = 'ADD_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const DELETE_USER_INFO = 'DELETE_USER_INFO';
// export const TOGGLE_USER_DIALOG = 'TOGGLE_USER_DIALOG';
// export const SELECT_USER_INFO = 'SELECT_USER';
// export const SELECT_ALL_USERS = 'SELECT_ALL_USERS';